namespace Common.Entities
{
    public class CartItem {

        public int SellerId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; } = "";
        public float UnitPrice { get; set; }
        public float FreightValue { get; set; }
        public int Quantity { get; set; }

        // Vouchers to be applied
        // coupons for different sellers attached to cart items
        // no formal voucher tracking in the benchmark
        // not a managed entity randomly generated by the driver
        public float[] Vouchers { get; set; } = new float[0];

        public CartItem() { }
    }
}